---
vision_one_script_src: "{{ playbook_dir }}/group_vars/deployment_script.ps1"

vision_one_script_dest: "C:\\Windows\\Temp\\deployment_script.ps1"

vision_one_use_proxy: false
vision_one_proxy_url: "http://proxy.example.local:3128"

vision_one_service_names_windows:
    - "tmlisten"
    - "ntrtscan"