; [vision_one_linux]
; web01.example.local ansible_host=10.10.1.11
; web02.example.local ansible_host=10.10.1.12

; [vision_one_linux:vars]
; ansible_user=deploy
; ansible_become=true

[vision_one_windows]
win01.example.local ansible_host=10.10.1.31
win02.example.local ansible_host=10.10.1.32

[vision_one_windows:vars]
ansible_user=Administrator
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
ansible_port=5986
