[apex_one_windows]
10.100.36.14[7:8]

[apex_one_windows:vars]
ansible_user=Administrator
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5985
ansible_winrm_scheme=http
ansible_password=P@ssw0rd