[apex_one_windows]
windows-home ansible_host=DESKTOP-PI6EBAV

[apex_one_windows:vars]
ansible_user=Administrator
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5985
ansible_winrm_scheme=http
ansible_password=210329
ansible_winrm_operation_timeout_sec=600
ansible_winrm_read_timeout_sec=660